In [1]:
import numpy as np

In [2]:
# reate a 3D NumPy array of shape (2,3,4) filled with integers from 1 to 24, and reshape it without using loops

arr=np.arange(1,25).reshape(2,3,4)
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
# Generate a 5×5 array with random integers between 10 and 50, then extract all even numbers using boolean masking.


import numpy as np

random_array = np.random.randint(10, 51, size=(5, 5))
print("Generated 5x5 array:")
print(random_array)

Generated 5x5 array:
[[40 31 33 41 10]
 [30 36 42 37 42]
 [25 48 19 18 41]
 [32 32 45 39 22]
 [38 34 18 12 10]]


In [ ]:
# Create two arrays a = np.arange(1,13).reshape(3,4) and b = np.array([10,20,30,40]). Use broadcasting to add b to every row of a.

a=np.arange(1,13).reshape(3,4)
b=np.array([10,20,30,40])
print(a+b)


[[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


In [ ]:
#  Construct a 6×6 identity matrix and replace its secondary diagonal (from top-right to bottom-left) with all 7’s.

Identity_matrix = np.identity(6)
# print(Identity_matrix)
Identity_matrix[np.arange(6), np.arange(5, -1, -1)] = 7
print(Identity_matrix)

[[1. 0. 0. 0. 0. 7.]
 [0. 1. 0. 0. 7. 0.]
 [0. 0. 1. 7. 0. 0.]
 [0. 0. 7. 1. 0. 0.]
 [0. 7. 0. 0. 1. 0.]
 [7. 0. 0. 0. 0. 1.]]


In [ ]:
# Generate 20 linearly spaced numbers between -5 and 5. Reshape into a (4,5) array and extract only the elements greater than 0.

linspace_array = np.linspace(-5, 5, 20).reshape(4, 5)
print(linspace_array)

elements_greater_than_0 = linspace_array[linspace_array > 0]
print(elements_greater_than_0)

[[-5.         -4.47368421 -3.94736842 -3.42105263 -2.89473684]
 [-2.36842105 -1.84210526 -1.31578947 -0.78947368 -0.26315789]
 [ 0.26315789  0.78947368  1.31578947  1.84210526  2.36842105]
 [ 2.89473684  3.42105263  3.94736842  4.47368421  5.        ]]
[0.26315789 0.78947368 1.31578947 1.84210526 2.36842105 2.89473684
 3.42105263 3.94736842 4.47368421 5.        ]


In [ ]:
# Create a 4x4 array with numbers from 1 to 16. Swap the first and last rows using slicing.

arr = np.arange(1, 17).reshape(4, 4)
print(arr)

arr[[0, 3], :] = arr[[3, 0], :]
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[13 14 15 16]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


In [ ]:
# Create a 10×10 array with random floats between 0 and 1, then find the row with the maximum sum.

arr = np.random.rand(10, 10)
print(arr)

row_with_max_sum = np.argmax(np.sum(arr, axis=1))
print(row_with_max_sum)

[[0.77339953 0.9121255  0.15321851 0.89830865 0.84397659 0.80655092
  0.53500806 0.61654257 0.08838468 0.73635496]
 [0.1528321  0.7892189  0.42258874 0.06546421 0.69037775 0.04739638
  0.89754829 0.86403495 0.52057629 0.60344535]
 [0.99583483 0.69073906 0.60231031 0.67426927 0.34505797 0.94652922
  0.84349029 0.07557688 0.70071274 0.58301215]
 [0.97646383 0.36381394 0.53681222 0.99132117 0.91983315 0.04386106
  0.98025311 0.71169224 0.36952264 0.14989875]
 [0.30938101 0.93167801 0.33951817 0.68460548 0.96068223 0.05129622
  0.45127221 0.39905207 0.75704591 0.65116084]
 [0.44160084 0.91163912 0.89377663 0.69026944 0.78376203 0.39925445
  0.75414635 0.49372698 0.65910868 0.24411297]
 [0.29437097 0.48133765 0.63144986 0.0125605  0.00324359 0.90645351
  0.59199142 0.62224779 0.04665872 0.94045973]
 [0.10657773 0.29352782 0.66998055 0.6861672  0.48780625 0.85750493
  0.00509013 0.58541471 0.24500738 0.0595435 ]
 [0.40143767 0.13621074 0.68408066 0.99945122 0.32551092 0.49900364
  0.13783664

In [ ]:
# Given arr = np.arange(1,26).reshape(5,5), extract the submatrix of even numbers only, keeping their 2D structure.

arr = np.arange(1, 26).reshape(5, 5)
print(arr)

even_submatrix = arr[arr % 2 == 0]
print(even_submatrix)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 2  4  6  8 10 12 14 16 18 20 22 24]


In [ ]:
# Generate two arrays a = np.array([1,2,3]) and b = np.array([[10],[20],[30]]). Perform multiplication using broadcasting and explain the result.

a = np.array([1,2,3])
b = np.array([[10],[20],[30]])
print(a*b)

[[10 20 30]
 [20 40 60]
 [30 60 90]]


In [ ]:
# Create a diagonal matrix with values [5,10,15,20]. Then convert it into a full 4×4 matrix where diagonal values remain but others are filled with -1.


diagonal_values = [5, 10, 15, 20]
diag_matrix = np.diag(diagonal_values)
print(diag_matrix)

full_matrix = np.full((4, 4), -1)
np.fill_diagonal(full_matrix, diagonal_values)
print(full_matrix)

In [ ]:
# using np.eye(5), create a 5×5 matrix with diagonal values equal to multiples of 3.

diagonal_values = np.arange(1, 6) * 3
matrix = np.diag(diagonal_values)
print(matrix)

[[ 3  0  0  0  0]
 [ 0  6  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 12  0]
 [ 0  0  0  0 15]]


In [ ]:
# Construct an array of shape (3,4,2) with values from 1 to 24. Flatten it using ravel(), and then reshape it into (2,3,4).
arr = np.arange(1, 25).reshape(3, 4, 2)
print(arr)

flat = arr.ravel()
print( flat)
reshaped = flat.reshape(2, 3, 4)
print( reshaped)


[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
# Generate a 7×7 matrix of random integers (1–100). Replace all values divisible by 5 with -5 using boolean indexing.

import numpy as np

random_matrix = np.random.randint(1, 101, size=(7, 7))
modified_matrix = random_matrix.copy()
divisible_by_5_mask = random_matrix % 5 == 0
modified_matrix[divisible_by_5_mask] = -5
print("Original Matrix:")
print(random_matrix)
print("\n" + "="*45 + "\n")
print("Modified Matrix (values divisible by 5 replaced with -5):")
print(modified_matrix)

Original Matrix:
[[47 95  1 30 92 45 21]
 [45 92  7 47 85 78  8]
 [ 1 38  3 33 92 23 40]
 [77 48 23 30 56 96 33]
 [52 80 51 64 85 91 22]
 [44 91 85  7 35 95 77]
 [79 20 81 33 34 38 49]]


Modified Matrix (values divisible by 5 replaced with -5):
[[47 -5  1 -5 92 -5 21]
 [-5 92  7 47 -5 78  8]
 [ 1 38  3 33 92 23 -5]
 [77 48 23 -5 56 96 33]
 [52 -5 51 64 -5 91 22]
 [44 91 -5  7 -5 -5 77]
 [79 -5 81 33 34 38 49]]


In [5]:
#Given arr = np.linspace(0, 2*np.pi, 10), compute sine and cosine values for each element and stack them into a 2D array with shape (10,2).

import numpy as np
arr = np.linspace(0, 2*np.pi, 10)
sine_values = np.sin(arr)
cosine_values = np.cos(arr)
stacked_array = np.column_stack((sine_values, cosine_values))
print("Final Stacked Array (shape {}):".format(stacked_array.shape))
print(stacked_array)

Final Stacked Array (shape (10, 2)):
[[ 0.00000000e+00  1.00000000e+00]
 [ 6.42787610e-01  7.66044443e-01]
 [ 9.84807753e-01  1.73648178e-01]
 [ 8.66025404e-01 -5.00000000e-01]
 [ 3.42020143e-01 -9.39692621e-01]
 [-3.42020143e-01 -9.39692621e-01]
 [-8.66025404e-01 -5.00000000e-01]
 [-9.84807753e-01  1.73648178e-01]
 [-6.42787610e-01  7.66044443e-01]
 [-2.44929360e-16  1.00000000e+00]]


In [4]:
# Create a 5×5 checkerboard pattern (alternating 0s and 1s) using slicing, without manually typing  each element.

checkerboard = np.zeros((5, 5))
checkerboard[::2, ::2] = 1
checkerboard[1::2, 1::2] = 1
print(checkerboard)

[[1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]]
